import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/Container";
const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="fixed top-0 w-screen py-5 border-b-2 border-black shadow-lg bg-white">
          <Container>
            <div>
              <Link
                href="/"
                className="flex gap-1 items-center text-lg hover:font-bold hover:underline"
              >
                <Image
                  src="/assets/rigo.png"
                  alt="Rigo"
                  width={30}
                  height={30}
                />

                <span>Docs</span>
              </Link>
            </div>
          </Container>
        </nav>
        {children}
      </body>
    </html>
  );
}
